### ISSUE TITLE
Build forked PRs

### ISSUE THREAD

**Issue by jonallured** [jonallured/braze_ruby#35]
Due to the way I'm publishing this gem via CircleCI, I have disabled building forked PRs. There's a better way! What I'd like to move to is using CircleCI for building and verifying PRs and then GitHub Actions to do the publishing. That way I can update the CircleCI config to remove any credentials and build across forks without my token being exposed.

**Comment by brrusselburg** [comment]
Would this update have affected the ability to rebase a fork? I was able to pull down the updated master (confirmed in the logs), but I get an error message when I attempt to rebase my branch.

`` ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/gem_credentials` without `workflow` scope)``

I updated my PAT to include the workflow scope, and it regenerated a new one for me. Sorry if I'm missing something obvious here!

**Comment by jonallured** [comment]
@brrusselburg whoaaa that's weird!! I can't tell for sure what it's trying to warn us about but does your diff include a change to that gem creds file?? I can't imagine it would. 🤔

**Comment by brrusselburg** [comment]
> @brrusselburg whoaaa that's weird!! I can't tell for sure what it's trying to warn us about but does your diff include a change to that gem creds file?? I can't imagine it would. 🤔

Double-checked in case something weird happened, but nope. Also confirmed that the changes _are_ now on my branch with my changes. It just doesn't like me `push`ing for some reason.

**Comment by brrusselburg** [comment]
> > @brrusselburg whoaaa that's weird!! I can't tell for sure what it's trying to warn us about but does your diff include a change to that gem creds file?? I can't imagine it would. 🤔
> 
> Double-checked in case something weird happened, but nope. Also confirmed that your recent changes _are_ now on my branch with my changes. It just doesn't like me `push`ing for some reason.

Fixed! In case anyone else runs into this, my git config was HTTPS. Changing it to SSH fixed the issue /shrug

**Comment by jonallured** [comment]
Wow, nice catch! Thanks for following up 👍
